name: ci

on: 
  push:
    branches: '**'
  schedule:
    - cron:  '0 0 * * *'

jobs:
  path-context:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      -
        name: r-ver-ubuntu
        uses: docker/build-push-action@v2
        with:
          context: r-ver-ubuntu
          file: r-ver-ubuntu/Dockerfile
          push: true
          tags: inwt/r-ver-ubuntu:${{ steps.extract_branch.outputs.branch }}
      -
        name: r-base
        uses: docker/build-push-action@v2
        with:
          context: r-base
          file: r-base/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/386
          push: true
          tags: inwt/r-base:${{ steps.extract_branch.outputs.branch }}
      -
        name: r-batch
        uses: docker/build-push-action@v2
        with:
          context: r-batch
          file: r-batch/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/386
          push: true
          tags: inwt/r-batch:${{ steps.extract_branch.outputs.branch }}
      -
        name: r-shiny
        uses: docker/build-push-action@v2
        with:
          context: r-shiny
          file: r-shiny/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/386
          push: true
          tags: inwt/r-shiny:${{ steps.extract_branch.outputs.branch }}
      -
        name: r-model
        uses: docker/build-push-action@v2
        with:
          context: r-model
          file: r-model/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/386
          push: true
          tags: inwt/r-model:${{ steps.extract_branch.outputs.branch }}
          
